# Dockerfile.worker
FROM node:22-alpine

WORKDIR /app

# Copy package files and install only production deps
COPY package*.json ./
RUN npm install --omit=dev

# Copy necessary files
COPY dist ./dist
COPY prisma ./prisma
COPY generated/prisma ./generated/prisma
COPY .env .env

# Generate Prisma client for Linux (Railway)
RUN npx prisma generate

# Ensure uploads folder exists (optional)
RUN mkdir -p /app/uploads/images

# Start the worker
CMD ["node", "dist/jobs/workers/cacheWorker.js"]
